// Frequently impersonated brands and the registrable domains they really use.
// `anyTld: true` means "<key>.<any public suffix>" is legitimate (e.g. the
// many Amazon country stores). Keys are the tokens we look for in hostnames.
export const BRANDS = [
  { key: "paypal", domains: ["paypal.com", "paypal.me", "paypalobjects.com"], anyTld: true },
  { key: "apple", domains: ["apple.com", "icloud.com", "apple.news", "mzstatic.com"] },
  { key: "icloud", domains: ["icloud.com", "apple.com"] },
  { key: "appleid", domains: ["apple.com"] },
  { key: "microsoft", domains: ["microsoft.com", "microsoftonline.com", "live.com", "office.com", "azure.com", "msn.com", "bing.com", "xbox.com"] },
  { key: "office365", domains: ["office.com", "microsoft.com", "office365.com"] },
  { key: "outlook", domains: ["outlook.com", "live.com", "office.com", "microsoft.com"] },
  { key: "onedrive", domains: ["live.com", "onedrive.com", "microsoft.com", "sharepoint.com"] },
  { key: "sharepoint", domains: ["sharepoint.com", "microsoft.com"] },
  { key: "google", domains: ["google.com", "gmail.com", "youtube.com", "gstatic.com", "googleapis.com", "withgoogle.com", "goo.gl", "g.co"], anyTld: true },
  { key: "gmail", domains: ["gmail.com", "google.com"] },
  { key: "youtube", domains: ["youtube.com", "youtu.be", "google.com"] },
  { key: "amazon", domains: ["amazon.com", "amazon.co.uk", "amazon.in", "amazon.de", "aws.amazon.com", "a2z.com", "amazon.jobs"], anyTld: true },
  { key: "facebook", domains: ["facebook.com", "fb.com", "fb.me", "fbcdn.net", "meta.com", "messenger.com"] },
  { key: "instagram", domains: ["instagram.com", "cdninstagram.com", "meta.com"] },
  { key: "whatsapp", domains: ["whatsapp.com", "whatsapp.net", "wa.me", "meta.com"] },
  { key: "meta", domains: ["meta.com", "meta.ai", "facebook.com"] },
  { key: "netflix", domains: ["netflix.com", "nflxext.com", "nflximg.net"] },
  { key: "linkedin", domains: ["linkedin.com", "licdn.com", "lnkd.in"] },
  { key: "twitter", domains: ["twitter.com", "x.com", "t.co", "twimg.com"] },
  { key: "dropbox", domains: ["dropbox.com", "dropboxusercontent.com", "db.tt"] },
  { key: "docusign", domains: ["docusign.com", "docusign.net"] },
  { key: "adobe", domains: ["adobe.com", "adobelogin.com", "typekit.net", "acrobat.com"] },
  { key: "chase", domains: ["chase.com", "jpmorganchase.com", "jpmorgan.com"] },
  { key: "bankofamerica", domains: ["bankofamerica.com", "bofa.com"] },
  { key: "wellsfargo", domains: ["wellsfargo.com", "wf.com"] },
  { key: "citibank", domains: ["citi.com", "citibank.com", "citigroup.com"] },
  { key: "hsbc", domains: ["hsbc.com", "hsbc.co.uk", "hsbc.com.hk"], anyTld: true },
  { key: "barclays", domains: ["barclays.co.uk", "barclays.com"] },
  { key: "santander", domains: ["santander.co.uk", "santander.com", "santanderbank.com"], anyTld: true },
  { key: "americanexpress", domains: ["americanexpress.com", "aexp.com"] },
  { key: "amex", domains: ["americanexpress.com", "amex.com"] },
  { key: "capitalone", domains: ["capitalone.com"] },
  { key: "coinbase", domains: ["coinbase.com"] },
  { key: "binance", domains: ["binance.com", "binance.us"] },
  { key: "kraken", domains: ["kraken.com"] },
  { key: "metamask", domains: ["metamask.io"] },
  { key: "ledger", domains: ["ledger.com"] },
  { key: "trezor", domains: ["trezor.io"] },
  { key: "blockchain", domains: ["blockchain.com"] },
  { key: "dhl", domains: ["dhl.com", "dhl.de", "dhl.co.uk"], anyTld: true },
  { key: "fedex", domains: ["fedex.com"] },
  { key: "usps", domains: ["usps.com"] },
  { key: "royalmail", domains: ["royalmail.com"] },
  { key: "steam", domains: ["steampowered.com", "steamcommunity.com", "steamstatic.com", "steamgames.com"] },
  { key: "steamcommunity", domains: ["steamcommunity.com"] },
  { key: "roblox", domains: ["roblox.com", "rbxcdn.com"] },
  { key: "discord", domains: ["discord.com", "discord.gg", "discordapp.com", "discord.media"] },
  { key: "telegram", domains: ["telegram.org", "t.me", "telegram.me"] },
  { key: "spotify", domains: ["spotify.com", "scdn.co"] },
  { key: "ebay", domains: ["ebay.com", "ebay.co.uk", "ebaystatic.com"], anyTld: true },
  { key: "walmart", domains: ["walmart.com"] },
  { key: "github", domains: ["github.com", "githubusercontent.com", "githubassets.com"] },
  { key: "openai", domains: ["openai.com", "chatgpt.com"] },
  { key: "yahoo", domains: ["yahoo.com", "yimg.com"], anyTld: true },
  { key: "irs", domains: ["irs.gov"] },
  { key: "zoom", domains: ["zoom.us", "zoom.com"] },
  { key: "okta", domains: ["okta.com", "oktacdn.com"] },
  { key: "venmo", domains: ["venmo.com"] },
  { key: "cashapp", domains: ["cash.app", "squareup.com"] },
  { key: "stripe", domains: ["stripe.com"] },
  { key: "booking", domains: ["booking.com"] },
  { key: "airbnb", domains: ["airbnb.com"], anyTld: true },
];

/** Known URL shorteners: not malicious, but they hide the destination. */
export const URL_SHORTENERS = new Set([
  "bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly", "is.gd", "buff.ly", "rebrand.ly", "cutt.ly",
  "shorturl.at", "rb.gy", "tiny.cc", "lnkd.in", "s.id", "v.gd", "t.ly", "bl.ink", "short.io",
]);

/** TLDs with consistently high abuse rates in public phishing/malware feeds. */
export const HIGH_ABUSE_TLDS = new Set([
  "zip", "mov", "top", "xyz", "tk", "ml", "ga", "cf", "gq", "buzz", "rest", "cam", "icu",
  "monster", "cfd", "sbs", "click", "link", "country", "kim", "work", "support", "quest",
  "lol", "bond", "cyou", "beauty", "hair", "skin", "makeup", "autos", "boats", "yachts",
  "mom", "bar", "pw", "cc", "su", "ws", "gdn", "loan", "men", "date", "win", "bid", "stream",
  "download", "racing", "review", "accountant", "science", "party", "trade", "webcam", "zone",
]);
