// Network-level protection with declarativeNetRequest.
//
// Static rulesets (generated by scripts/update-blocklists.mjs):
//   nv_ads     — ad & tracker hosts, third-party sub-resources only
//   nv_malware — malware/phishing hosts; top-level navigations are redirected
//                to the NULL VOID interstitial, everything else is blocked
// Dynamic rules: user trusted sites (allowAllRequests), user-blocked sites,
// optional HTTPS upgrade. Session rules: one-off "proceed anyway" exceptions.

import { api, isWebUrl } from "../lib/browser.js";
import { getSettings, updateSettings, onSettingsChanged } from "../lib/settings.js";
import { registrableDomain, normalizeHost } from "../lib/domain.js";
import { logEvent, bumpStat } from "../lib/events.js";
import { handle } from "./router.js";

const DNR = api.declarativeNetRequest;
// Large lists are split across several ruleset files (nv_malware_1, _2, …).
const DECLARED = (api.runtime.getManifest().declarative_net_request?.rule_resources ?? []).map((r) => r.id);
export const RULESETS = {
  ads: DECLARED.filter((id) => id.startsWith("nv_ads")),
  malware: DECLARED.filter((id) => id.startsWith("nv_malware")),
};
const groupOf = (rulesetId) => (rulesetId?.startsWith("nv_ads") ? "ads" : rulesetId?.startsWith("nv_malware") ? "malware" : "custom");

const RULE_TRUSTED = 1000;
const RULE_HTTPS_UPGRADE = 1001;
const RULE_BLOCKED_REDIRECT = 1002;
const RULE_BLOCKED_SUB = 1003;
const SESSION_BASE = 5000;
const PROCEED_KEY = "nv.proceed"; // storage.session: host -> ruleId

const BLOCK_SUB_TYPES = ["sub_frame", "script", "stylesheet", "image", "font", "object", "xmlhttprequest", "ping", "media", "websocket", "other"];

export async function applyProtection(settings) {
  if (!DNR) return;
  const p = settings.protection;
  const enable = [], disable = [];
  (p.enabled && p.ads ? enable : disable).push(...RULESETS.ads);
  (p.enabled && p.malware ? enable : disable).push(...RULESETS.malware);
  try {
    await DNR.updateEnabledRulesets({ enableRulesetIds: enable, disableRulesetIds: disable });
  } catch (err) {
    console.warn("[NULL VOID] ruleset update failed", err);
  }

  const addRules = [];
  const trusted = [...new Set(p.trustedSites.map(normalizeHost).filter(Boolean))];
  if (trusted.length) {
    addRules.push({
      id: RULE_TRUSTED, priority: 10000,
      action: { type: "allowAllRequests" },
      condition: { requestDomains: trusted, resourceTypes: ["main_frame", "sub_frame"] },
    });
  }
  const blocked = [...new Set(p.blockedSites.map(normalizeHost).filter(Boolean))];
  if (p.enabled && blocked.length) {
    addRules.push({
      id: RULE_BLOCKED_REDIRECT, priority: 9000,
      action: { type: "redirect", redirect: { extensionPath: "/blocked/blocked.html?mode=list&list=custom" } },
      condition: { requestDomains: blocked, resourceTypes: ["main_frame"] },
    });
    addRules.push({
      id: RULE_BLOCKED_SUB, priority: 9000,
      action: { type: "block" },
      condition: { requestDomains: blocked, resourceTypes: BLOCK_SUB_TYPES },
    });
  }
  if (p.enabled && p.httpsUpgrade) {
    addRules.push({
      id: RULE_HTTPS_UPGRADE, priority: 1,
      action: { type: "upgradeScheme" },
      condition: {
        regexFilter: "^http://[^/]+",
        excludedRequestDomains: ["localhost", "127.0.0.1", "0.0.0.0", "local", "lan", "internal", "home.arpa"],
        resourceTypes: ["main_frame"],
      },
    });
  }
  const existing = await DNR.getDynamicRules();
  await DNR.updateDynamicRules({ removeRuleIds: existing.map((r) => r.id), addRules });

  // Per-tab blocked-request count on the toolbar badge (Chromium).
  try {
    await DNR.setExtensionActionOptions?.({ displayActionCountAsBadgeText: p.enabled });
    await api.action.setBadgeBackgroundColor({ color: "#2f6df6" });
  } catch { /* unsupported (Firefox) */ }
}

export async function isTrusted(url) {
  if (!isWebUrl(url)) return false;
  const host = normalizeHost(new URL(url).hostname);
  const { protection } = await getSettings();
  return protection.trustedSites.some((d) => host === d || host.endsWith(`.${d}`));
}

/** Allow one host for this browser session (after an explicit user choice). */
export async function allowForSession(host) {
  host = normalizeHost(host);
  const { [PROCEED_KEY]: map = {} } = await api.storage.session.get(PROCEED_KEY);
  if (map[host]) return map[host];
  const used = new Set(Object.values(map));
  let id = SESSION_BASE;
  while (used.has(id)) id++;
  await DNR.updateSessionRules({
    removeRuleIds: [id],
    addRules: [{
      id, priority: 20000,
      action: { type: "allowAllRequests" },
      condition: { requestDomains: [host], resourceTypes: ["main_frame", "sub_frame"] },
    }],
  });
  map[host] = id;
  await api.storage.session.set({ [PROCEED_KEY]: map });
  return id;
}

export async function isAllowedForSession(host) {
  const { [PROCEED_KEY]: map = {} } = await api.storage.session.get(PROCEED_KEY);
  host = normalizeHost(host);
  return Object.keys(map).some((h) => host === h || host.endsWith(`.${h}`));
}

async function matchedCount(tabId) {
  try {
    const { rulesMatchedInfo } = await DNR.getMatchedRules({ tabId });
    const counts = { ads: 0, malware: 0, custom: 0 };
    for (const m of rulesMatchedInfo) counts[groupOf(m.rule.rulesetId)]++;
    return counts;
  } catch {
    const text = await api.action.getBadgeText({ tabId }).catch(() => "");
    return { ads: Number(text) || 0, malware: 0, custom: 0, approximate: true };
  }
}

// --- Message handlers ----------------------------------------------------------

handle("protection:status", async ({ tabId }) => {
  const settings = await getSettings();
  const enabledRulesets = DNR ? await DNR.getEnabledRulesets() : [];
  const available = DNR?.getAvailableStaticRuleCount ? await DNR.getAvailableStaticRuleCount().catch(() => null) : null;
  return {
    protection: settings.protection,
    rulesets: enabledRulesets,
    availableStaticRules: available,
    matched: tabId != null ? await matchedCount(tabId) : null,
  };
});

handle("protection:setTrusted", async ({ host, trusted }) => {
  const domain = registrableDomain(host);
  const s = await getSettings();
  const set = new Set(s.protection.trustedSites);
  if (trusted) set.add(domain);
  else set.delete(domain);
  await updateSettings({ protection: { trustedSites: [...set].sort() } });
  await logEvent({ type: "trust", severity: "info", title: `${trusted ? "Trusted" : "Removed trust for"} ${domain}` });
  return { domain, trusted };
});

handle("protection:setBlocked", async ({ host, blocked }) => {
  const domain = registrableDomain(host);
  const s = await getSettings();
  const set = new Set(s.protection.blockedSites);
  if (blocked) set.add(domain);
  else set.delete(domain);
  await updateSettings({ protection: { blockedSites: [...set].sort() } });
  await logEvent({ type: "block-site", severity: "info", title: `${blocked ? "Blocked" : "Unblocked"} ${domain}` });
  return { domain, blocked };
});

handle("protection:proceed", async ({ url }, sender) => {
  if (!isWebUrl(url)) throw new Error("Invalid URL");
  const host = new URL(url).hostname;
  await allowForSession(host);
  await logEvent({ type: "proceed", severity: "medium", title: `Proceeded to ${host} despite a warning`, url });
  await bumpStat("warningsOverridden");
  if (sender.tab?.id != null) await api.tabs.update(sender.tab.id, { url });
  return { ok: true };
});

// Keep DNR in sync with settings.
onSettingsChanged((next, prev) => {
  if (JSON.stringify(next.protection) !== JSON.stringify(prev.protection)) applyProtection(next).catch(console.error);
});
