// Browserless.io Configuration
// Auto-generated by deploy-browserless.js

const BROWSERLESS_CONFIG = {
    apiKey: "2SgiPLlAtLyabl75ea63edb2fb15fcf000d866d90aa96ab13",
    baseUrl: "https://chrome.browserless.io",
    wsUrl: "wss://chrome.browserless.io",
    timeout: 30000,
    maxRetries: 3,
    
    // API endpoints
    endpoints: {
        screenshot: "/screenshot",
        content: "/content",
        pdf: "/pdf",
        function: "/function",
        scrape: "/scrape",
        version: "/json/version"
    },
    
    // Default options
    defaultOptions: {
        screenshot: {
            type: 'png',
            quality: 90,
            fullPage: false
        },
        gotoOptions: {
            waitUntil: 'networkidle2',
            timeout: 30000
        }
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = BROWSERLESS_CONFIG;
}

// Make available globally
window.BROWSERLESS_CONFIG = BROWSERLESS_CONFIG;
